version: '3.3'
services:
  api:
    build: ./
    container_name: laravel
    ports:
      - "9000:80"
    volumes:
      - ./:/usr/share/nginx/html
    restart: always
    depends_on:
      - db
    networks: 
      - docker
  
  app:
    build:
      context: ./
      dockerfile: ./html/Dockerfile
    container_name: vue
    ports:
      - "8080:8080"
    volumes:
      - ./html:/app
    networks: 
      - docker
    

  db:
    image: mysql
    restart: always
    ports: 
      - 3333:3306
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    volumes:
      - .docker/dbdata:/var/lib/mysql
    networks:
      - docker

networks:
  docker:
    driver: bridge
