version: '3.3'
services:
  projeto-alunos:
    build: ./
    ports:
      - "9000:80"
    volumes:
      - ./:/usr/share/nginx/html
    restart: always
    depends_on:
      - db
    networks: 
      - docker

  db:
    image: mysql
    restart: always
    ports: 
      - 3333:3306
    environment:
      MYSQL_ROOT_PASSWORD: docker
      MYSQL_DATABASE: docker
      MYSQL_USER: docker
      MYSQL_PASSWORD: docker
    volumes:
      - .docker/dbdata:/var/lib/mysql
    networks:
      - docker

networks:
  docker:
    driver: bridge
